name: Playwright Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Create .env file
      run: |
        echo "URL_PADRAO=${{ secrets.URL_PADRAO }}" >> .env
        echo "URL_RANDOM=${{ secrets.URL_RANDOM }}" >> .env
        echo "RACA_DOG=${{ secrets.RACA_DOG }}" >> .env

    - name: Run Playwright tests
      run: npm run test:e2e || true

    - name: Generate Allure Report
      if: always()
      run: npm run allure:generate

    - name: Upload Allure Results Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results
        retention-days: 10

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action
      uses: simple-elf/allure-report-action@v1.9
      if: always()
      with:
        allure_results: allure-results
            

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
        publish_branch: gh-pages
